//------------------------------------------------------------------------------
// <auto-generated>
//     Minimal, dependency-free subset of the XrmTools.Meta.Attributes package.
//
//     Emitted by the Plugin Step Codegen tool for XrmToolBox so
//     that generated [Plugin] / [Step] / [Image] attributes compile without
//     installing the XrmTools.Meta.Attributes NuGet package or the Xrm Tools
//     Visual Studio extension.
//
//     Namespace, type names, constructor signatures, property names and enum
//     values are identical to the published package, so this file can be
//     deleted at any time and replaced by:
//
//         <PackageReference Include="XrmTools.Meta.Attributes" Version="1.0.57" />
//
//     Do NOT keep both this file and the NuGet package in the same project:
//     the package generates these same types into your compilation and you
//     will get CS0101 (duplicate type) errors.
//
//     Types are declared 'internal' to match the package default. The package
//     switches to public via <XrmToolsMetaAttributesUsePublicAccessibility>;
//     if you need that here, change the modifiers below by hand.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmTools.Meta.Attributes
{
    using System;

    /// <summary>
    /// Read more about the stages of a plugin execution pipeline at
    /// https://learn.microsoft.com/en-us/power-apps/developer/data-platform/event-framework#event-execution-pipeline
    /// </summary>
    internal enum Stages
    {
        /// <summary>
        /// This provides an opportunity to include logic to cancel the operation before the database transaction.
        /// </summary>
        PreValidation = 10,
        /// <summary>
        /// Occurs before the main system operation and within the database transaction. (ownerid cannot be changed).
        /// </summary>
        PreOperation = 20,
        /// <summary>
        /// Main operation (custom API and Custom virtual table data providers).
        /// </summary>
        MainOperation = 30,
        /// <summary>
        /// Occurs after the main system operation and within the database transaction.
        /// </summary>
        PostOperation = 40
    }

    internal enum ExecutionMode
    {
        Synchronous = 0,
        Asynchronous = 1
    }

    internal enum ImageTypes
    {
        PreImage = 0,
        PostImage = 1,
        Both = 2
    }

    internal enum PluginStepStates
    {
        Active = 0,
        Inactive = 1
    }

    internal enum SupportedDeployments
    {
        Server = 0,
        Client = 1,
        Both = 2
    }

    internal enum IsolationModes
    {
        [Obsolete]
        None = 1,
        Sandbox = 2,
        [Obsolete]
        External = 3
    }

    internal enum SourceTypes
    {
        Database = 0,
        Disk = 1,
        Normal = 2,
        AzureWebApp = 3,
        FileStore = 4
    }

    /// <summary>
    /// Apply this attribute to a plugin class to mark it for plugin registration. By default, the name will be
    /// inferred from the type's name, but you can specify the name explicitly, along with a description and
    /// other details.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
    internal class PluginAttribute : Attribute
    {
        public string Id { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string FriendlyName { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string WorkflowActivityGroupName { get; set; } = string.Empty;
    }

    /// <summary>
    /// Defines a plugin step for a plugin class, specifying the message, stage, execution mode, and other step
    /// configuration. The class that this attribute is applied to should have a <see cref="PluginAttribute" />
    /// before this attribute.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
    internal class StepAttribute : Attribute
    {
        // Constructor (aka positional) parameters
        public ExecutionMode Mode { get; set; }
        public Stages Stage { get; }
        public string MessageName { get; }

        // Named parameters
        public string PrimaryEntityName { get; set; } = string.Empty;
        public string FilteringAttributes { get; set; } = string.Empty;
        public string Id { get; set; } = string.Empty;
        public int ExecutionOrder { get; set; } = 1;
        public string ImpersonatingUserFullname { get; set; } = string.Empty;

        // WARNING - do not "fix" the two nullable properties below.
        //
        // C# forbids nullable enums as attribute named arguments (CS0655), so
        // SupportedDeployment and State can never actually be set in an attribute
        // usage. This is a defect in the upstream XrmTools.Meta.Attributes package
        // (reproduced against v1.0.57), faithfully mirrored here on purpose.
        //
        // Making them non-nullable would let code compile against THIS file but
        // fail against the real NuGet package - the exact incompatibility this
        // file exists to avoid. The generator must never emit these two names.
        public SupportedDeployments? SupportedDeployment { get; set; } = SupportedDeployments.Server;
        public PluginStepStates? State { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Configuration { get; set; } = string.Empty;
        public bool CanBeBypassed { get; set; } = false;
        public bool AsyncAutoDelete { get; set; } = false;

        public StepAttribute(string messageName, Stages stage, ExecutionMode mode)
        {
            MessageName = messageName;
            Stage = stage;
            Mode = mode;
        }

        public StepAttribute(string messageName, string primaryEntityName, Stages stage, ExecutionMode mode)
            : this(messageName, stage, mode)
        {
            PrimaryEntityName = primaryEntityName;
        }

        public StepAttribute(string messageName, string primaryEntityName, string filteringAttributes, Stages stage, ExecutionMode mode)
            : this(messageName, primaryEntityName, stage, mode)
        {
            FilteringAttributes = filteringAttributes;
        }
    }

    /// <summary>
    /// Defines an image for a plugin step, specifying the image type, attributes, and other image configuration.
    /// This attribute should only be applied after a <see cref="StepAttribute" /> to the class, and binds to the
    /// nearest preceding <see cref="StepAttribute" />.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
    internal class ImageAttribute : Attribute
    {
        public string Id { get; set; } = string.Empty;
        /// <summary>
        /// Type of image requested.
        /// </summary>
        public ImageTypes ImageType { get; set; }
        /// <summary>
        /// Name of the property on the Request message. E.g. "Target".
        /// </summary>
        public string MessagePropertyName { get; set; } = string.Empty;
        /// <summary>
        /// Name of SdkMessage processing step image.
        /// </summary>
        public string Name { get; set; } = string.Empty;
        /// <summary>
        /// Key name used to access the pre-image or post-image property bags in a step.
        /// </summary>
        public string EntityAlias { get; set; } = string.Empty;
        public string Attributes { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        public ImageAttribute(ImageTypes imageType)
        {
            ImageType = imageType;
            Name = imageType.ToString();
            EntityAlias = imageType.ToString();
        }

        public ImageAttribute(ImageTypes imageType, string attributes) : this(imageType)
        {
            Attributes = attributes;
        }
    }

    /// <summary>
    /// Specifies metadata for a plugin assembly, including its unique identifier, source type and isolation mode.
    /// Isolation mode is an assembly-level concern in Xrm Tools; there is no per-step equivalent.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly)]
    internal class PluginAssemblyAttribute : Attribute
    {
        public static SourceTypes DefaultSourceType = SourceTypes.Database;
        public static IsolationModes DefaultIsolationMode = IsolationModes.Sandbox;
        public string Id { get; set; } = string.Empty;
        public SourceTypes SourceType { get; set; } = DefaultSourceType;
        public IsolationModes IsolationMode { get; set; } = DefaultIsolationMode;
    }
}
